name: README Lint Check

on:
  pull_request:
    paths:
      - README.md

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: codespell README.md
